schema-version: v2
kind: plugin
metadata:
  name: robot-framework-plugin
  display-name: robot-framework-plugin
  description: Instalar o core do Robot Framework para desenvolver testes automatizados de aplicações mobile e web.
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Python
  repository: https://github.com/allanocosta/robot-framework-plugin.git
  stk-projects-only: false
  inputs:
    - label: Escreva o nome do seu projeto
      type: text
      name: project_name
      required: true
      default: project-name
      help: 'Informe o nome do seu projeto (e.g.: Example Robot Framework Tests)'
      global: true

    - label: Informe a versão do projeto
      type: text
      name: project_version
      default: 1.0.0
      global: true
      required: true

    - label: Informe a descrição do projeto
      type: text
      name: project_description
      default: Projeto de Testes com Robot Framework
      required: true

    - label: Informe o autor do projeto
      type: text
      name: project_author
      required: true

  global-computed-inputs:
    project_id: "{{project_name|replace(' ','_')|replace('/','-')|replace('\\\\','-')}}"

  hooks:
    - type: run
      trigger: after-render
      commands:
        - pip install -r requirements.txt